#!/usr/bin/env bash

temporary_playground=/tmp/playground

mkdir -p $temporary_playground

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$( (echo $temporary_playground && find ~/coding -mindepth 1 -maxdepth 1 -type d) | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    tmux new-window -t $selected_name:1 -c $selected -n "Editor"
    tmux send-keys -t $selected_name:1 "nvim" C-m

    tmux new-window -t $selected_name:2 -c $selected -n "Shell"
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
    tmux new-window -t $selected_name:1 -c $selected -n "Editor"
    tmux send-keys -t $selected_name:1 "nvim" C-m

    tmux new-window -t $selected_name:2 -c $selected -n "Shell"
fi

if [[ -z $TMUX ]]; then
    tmux attach-session -t $selected_name
else
    tmux switch-client -t $selected_name
fi

