[font]
size= 20.0
normal = { family = "CommitMono Nerd Font", style = "Regular" }
bold = { family = "CommitMono Nerd Font", style = "Bold" }
italic = { family = "CommitMono Nerd Font", style = "Italic" }
bold_italic = { family = "CommitMono Nerd Font", style = "Bold Italic" }

[general]
import = ["./theme.toml"]
